# network parameters
NAME: 'unet3d'
#
# Data is 192x192x192, 192 == 2**6 * 3
# Downsampling 4 times gives a spatial resolution of 12 x 12 x 12

NETWORK:
  N_INITIAL_FILTERS:  1
  NETWORK_DEPTH:  1
  RESIDUAL: False
  BLOCKS_PER_LAYER: 1
  BLOCKS_DEEPEST_LAYER: 1
  BALANCE_LOSS: True
  BATCH_NORM: True
  NUM_LABELS: 3
  REGULARIZE: 0.001

# training parameters:
N_MINIBATCH: 1
MINIBATCH_SIZE: 1
SAVE_ITERATION: 5000
REPORT_ITERATION: 1
SUMMARY_ITERATION: 1
BASE_LEARNING_RATE:  0.001
ITERATIONS: 50

TRAINING: False

# IO Parameters:
IO:
  TRAIN:
    FILE: '/home/cadams/DeepLearnPhysics/CodaLabHEPML/data/public_dat_1/train_5-6.hdf5'
    MAX: 4500
    NUM_THREADS: 4
  TEST:
    FILE: '/home/cadams/DeepLearnPhysics/CodaLabHEPML/data/public_dat_1/train_5-6.hdf5'
    MIN: 4500
    NUM_THREADS: 4

# General parameters:
LOGDIR: 'log/unet_3d_dev/'
RESTORE: False


