# network parameters
NAME: 'uresnet3d'
#
# Data is 192x192x192, 192 == 2**6 * 3
# Downsampling 4 times gives a spatial resolution of 12 x 12 x 12

NETWORK:
  N_INITIAL_FILTERS:  8
  NETWORK_DEPTH:  4
  RESIDUAL: False
  BLOCKS_PER_LAYER: 3
  BLOCKS_DEEPEST_LAYER: 8
  BALANCE_LOSS: True
  BATCH_NORM: True
  NUM_LABELS: 3
  REGULARIZE: 0.001

# training parameters:
N_MINIBATCH: 4
MINIBATCH_SIZE: 1
SAVE_ITERATION: 500
REPORT_ITERATION: 10
SUMMARY_ITERATION: 1
BASE_LEARNING_RATE:  0.001
TRAINING: True
ITERATIONS: 25000

# IO Parameters:
IO:
  TRAIN:
    FILE: '/home/cadams/DeepLearnPhysics/CodaLabHEPML/data/train_5-6.hdf5'
    MAX: 4500
    NUM_THREADS: 2
  TEST:
    FILE: '/home/cadams/DeepLearnPhysics/CodaLabHEPML/data/train_5-6.hdf5'
    MIN: 4500
    NUM_THREADS: 2

# General parameters:
LOGDIR: 'log/unet_3d/'
RESTORE: False


