# network parameters
NAME: 'uresnet3d'
#
# Data is 192x192x192, 192 == 2**6 * 3
# Downsampling 4 times gives a spatial resolution of 12 x 12 x 12

NETWORK:
  N_INITIAL_FILTERS:  2
  NETWORK_DEPTH:  1
  RESIDUAL: True
  BLOCKS_PER_LAYER: 1
  BLOCKS_DEEPEST_LAYER: 1
  BALANCE_LOSS: True
  BATCH_NORM: True
  NUM_LABELS: 3

# training parameters:
N_MINIBATCH: 1
MINIBATCH_SIZE: 4
SAVE_ITERATION: 5000
REPORT_ITERATION: 10
SUMMARY_ITERATION: 1
BASE_LEARNING_RATE:  0.001
ITERATIONS: 50

TRAINING: True

# IO Parameters:
IO:
  FILE: '/home/cadams/DeepLearnPhysics/CodaLabHEPML/data/public_dat_1/train_1-2.hdf5'
  TEST: True

# General parameters:
LOGDIR: 'log/log_dev/'
RESTORE: False


