# network parameters
NAME: 'uresnet3d'
#
# Data is 192x192x192, 192 == 2**6 * 3
# Downsampling 4 times gives a spatial resolution of 12 x 12 x 12

NETWORK:
  N_INITIAL_FILTERS:  2
  NETWORK_DEPTH:  2
  RESIDUAL_BLOCKS_PER_LAYER: 4
  RESIDUAL_BLOCKS_DEEPEST_LAYER: 4
  BALANCE_LOSS: True
  BATCH_NORM: True
  NUM_LABELS: 3

# training parameters:
N_MINIBATCH: 1
MINIBATCH_SIZE: 2
SAVE_ITERATION: 500
REPORT_ITERATION: 10
SUMMARY_ITERATION: 1
BASE_LEARNING_RATE:  0.001
TRAINING: True
ITERATIONS: 25000

# IO Parameters:
IO:
  TRAIN:
    FILE: '/home/cadams/DeepLearnPhysics/CodaLabComptetion/data/public_dat_1/train_1-2.hdf5'

# General parameters:
LOGDIR: 'log/log_uresnet_3d/'
RESTORE: False


