# network parameters
NAME: 'unet3d'
#
# Data is 192x192x192, 192 == 2**6 * 3
# Downsampling 4 times gives a spatial resolution of 12 x 12 x 12

NETWORK:
  N_INITIAL_FILTERS:  1
  NETWORK_DEPTH:  1
  # RESIDUAL: True
  RESIDUAL_BLOCKS_PER_LAYER: 1
  RESIDUAL_BLOCKS_DEEPEST_LAYER: 1
  BALANCE_LOSS: True
  BATCH_NORM: True
  NUM_LABELS: 4
  # REGULARIZE: 0.001

# training parameters:
N_MINIBATCH: 1
MINIBATCH_SIZE: 1
SAVE_ITERATION: 5000
REPORT_ITERATION: 1
SUMMARY_ITERATION: 1
BASE_LEARNING_RATE:  0.001
ITERATIONS: 50

TRAINING: True

# IO Parameters:
IO:
  TRAIN:
    PROFILE_IO: false
    # FILE: '/home/cadams/DeepLearnPhysics/SBNDEventIdentification/larcv_io_config/3d/full/lepton_seg/train_io.cfg'
    FILE: './larcv_io_config/train_io.cfg'
    FILLER: 'TrainIO'
    VERBOSITY: 3
    KEYWORD_DATA:  'main_data'
    KEYWORD_LABEL: 'main_label'

  TEST:
    PROFILE_IO: false
    # FILE: '/home/cadams/DeepLearnPhysics/SBNDEventIdentification/larcv_io_config/3d/full/lepton_seg/test_io.cfg'
    FILE: './larcv_io_config/test_io.cfg'
    FILLER: 'TestIO'
    VERBOSITY: 3
    KEYWORD_DATA:  'test_data'
    KEYWORD_LABEL: 'test_label'

# General parameters:
LOGDIR: 'log/unet_3d_dev/'
RESTORE: False


